description = "This is LA's blog."
keywords = ["Hugo", "FixIt", "blog", "LA"]

[author]
name = "LA"
email = "la-syh@qq.com"
link = "https://github.com/la-syh"
avatar = "/images/avatar.jpg"

[app]
title = ""

[header]

[header.title]
logo = ""

[home]

[home.profile]
enable = true

[customPartials]
head = [
  "inject/fixit-docs-bookmark.html",
]
