description = "This is my new Hugo FixIt site"
keywords = ["Hugo", "FixIt"]

[author]
name = "LA"
email = "la-syh@qq.com"
link = "https://github.com/la-syh"
avatar = "https://lruihao.cn/images/avatar.jpg"

[app]
title = "LA's Blog"

[header]

[header.title]
logo = "/hugo-fixit-starter1/images/fixit.min.svg"

[home]

[home.profile]
enable = true

[customPartials]
head = [
  "inject/fixit-docs-bookmark.html",
]
